### ISSUE TITLE
Queue Panel Goes Blank

### ISSUE THREAD

**Issue by xBenjo** [kyrie25/spicetify-queue-panel#2]
When having the queue open, songs near the top will randomly black out and sometimes overlap eachother not allowing me to see the songs. It gets worse when adding songs to the queue. Closing and opening the queue sometimes fixes it but reload is the only sure fire fix. 
![pic](https://github.com/kyrie25/spicetify-queue-panel/assets/138199616/c482555d-d1f5-444d-b0cd-1e9355b14f32)

I just found this extension and am really loving it.

**Comment by kyrie25** [comment]
Randomly black out? Did it just naturally happen or when you’re browsing through the client, scrolling the panel, changing songs, etc.

Would be helpful if you can provide screen recordings to reproduce the issue also.

**Comment by kyrie25** [comment]
I tried to mess around and seems like this worked for me, I'm not sure how it happened on our side but with the latest commit just slightly scrolling up and down should fix the issue, or the issue won’t appear at all. You can test it by installing the extension locally or wait a couple hours on Marketplace for it to update.

Let me know if the problem is resolved and I'll respond ASAP!

**Comment by xBenjo** [comment]
Haven't had a problem since thanks!
